# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff
        language: system
        types: [python]
        args: ["check", "."]
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff
        language: system
        types: [python]
        args: ["format", "."]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        args: ["--ignore-missing-imports"]
